# Generated by Django 5.1.4 on 2025-01-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customer_id_alter_goodcategory_id_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
