# Generated by Django 5.1.4 on 2025-01-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_recipient_checkout_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
