# Generated by Django 5.1.4 on 2025-01-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_deliverymethod_id_alter_good_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='name',
            new_name='title',
        ),
    ]
